title: "Technical Artist Roadmap"
summary: "テクニカルアーティストになるために必要なスキルセット・知識をまとめた資料になります。

テクニカルアーティストに求められる職能は多岐に渉りますが、共通に身に着けておくべき知識やスキルセットなどを網羅的にまとめた資料を目指しています。
大体この辺りを知っておけばテクニカルアーティストとして名乗っていいでしょうという指標となる資料として活用できれば幸いです。

※）これらの記事はChatGPTの力を借りながら、インターネット上の知識を見ながら勉強してまとめた記事になります。それぞれの単元については素人レベルであるため、正しい説明・わかりやすい解説などは、他の記事を参照ください。"
topics: ["Blender","Maya","Unity","UnrealEngine"]
published: false
price: 0
chapters:
  - 01_intro
  - 02_math
  - 03_physics
  - 04_art
  - 05_computer_science
  - 06_computer_graphics
